INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "djangocms4test",
    "filer",
    "easy_thumbnails",
    "cms",
    "menus",
    "classytags",
    "treebeard",
    "sekizai",
    "djangocms_admin_style",
    "django.contrib.admin",
]
